app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index
from .views import terima

urlpatterns = [
    path('', index),
    path('terima/', terima),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('project/', views.project, name='project'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('homepage.urls')),
    path('isian/', include('app.urls')),
]

app/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Schedule(models.Model):
    kategori = models.CharField(max_length = 25, null=True)
    kegiatan = models.CharField(max_length = 25, null=True)
    waktu = models.DateTimeField(null = True)
    tempat = models.CharField(max_length = 25, null=True)

    def __str__(self):
        return "{}. {}".fomat(self.id, self.activity)

homepage/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms
from . import models

class CreateSchedule(forms.ModelForm):
    class Meta:
        model = models.Schedule
        fields = {'kategori','kegiatan','waktu','tempat'}
    # hari = forms.CharField(label='Hari', max_length=100, required=True)
    # tanggal = forms.DateField(required=True)
    # jam = forms.TimeField(required=True)
    # kegiatan = forms.CharField(max_length = 100, required=True)
    # tempat = forms.CharField(max_length = 100, required=True)
    # kategori = forms.CharField(max_length = 100, required=True)
        labels = {
            'kategori':'Kategori',
            'kegiatan' : 'Kegiatan',
            'waktu' : 'Waktu',
            'tempat' : 'Tempat',
        }

        widgets = {
            'kategori': forms.TextInput(
                attrs={
                    'class': 'form-control',
                },
            ),
            'kegiatan':forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Masukkan nama kegiatan anda',
                },
            ),
            'waktu': forms.DateTimeInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'yyyy/mm/dd HH:MM'
                },
            ),
            'tempat': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Masukkan tempat kegiatan anda',
                },
            ),
        }
        

app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import CreateSchedule
from .models import Schedule
from . import forms

# Create your views here.
def index(request):
    form = forms.CreateSchedule(request.POST)
    if form.is_valid():
        form.save()
        return redirect('terima')

    context = {
        'form' : form
    }
    return render(request, 'form.html', context)

def terima(request):
    all = Schedule.objects.all()

    context = {
        'data':all
    }

    return render(request, 'schedule.html', context)

def delete(request, id):
    Schedule.objects.filter(id=id).delete()
    return redirect('terima')

# def index(request):   
#     createSchedule = CreateSchedule()
#     argument = {
#         'generated_html' : createSchedule
#     }
#     return render(request, 'form.html', argument)

# def terima(request):
#     x = request.POST.get('isian')
#     z = Schedule(hari = x)
#     z.save()
#     all = Schedule.objects.all()
#     argument = {
#         'data' : x,
#         'before' : all,
#     }
#     return render(request, 'schedule.html', argument)

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def project(request):
    return render(request, 'project.html')

app/templates/form.html
<html>
    Kegiatan
    <form method='POST' action='/isian/terima/'>
        {% csrf_token %}
        {% for fields in form %}
            {{ fields.label }}
            <br>
            {{ fields }}
            <br>
        {% endfor %}
        <input type='submit' class='btn btn-primary mb-2 float-right' value='Add'>
        <input type="submit" value='Submit'/>
        
    </form>
</html>

app/templates/schedule.html
<html>
    Hasil
    <table>
        {% for object in data %}
        <tr>
            <td>{{ object.kategori }}</td>
            <td>{{ object.kegiatan }}</td>
            <td>{{ object.waktu }}</td>
            <td>{{ object.tempat }}</td>
        </tr>
        {% endfor %}
    </table>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Profile</title>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row nav" id="home">
                <div class="fixed-top" class="navbar">
                    <div class="float-xs-left float-sm-left float-md-left float-lg-left navbar">
                        <a href="#home">Home</a>
                        <a href="#about">About</a>
                        <a href="#contact">Contact</a>
                        <a href="{% url 'homepage:project' %}">Project</a>
                    </div>
                </div>
            </div>

            <section class="name">
                <div class="row">
                    <div class="col-sm-12 col-md-6 col-lg-3 offset-lg-3">
                        <img id="profilepic" src="{% static 'images/profilepic.png' %}", alt="Profile Picture">
                    </div>
                    <div class="col-sm-12 col-md-6 col-lg-4">
                        <div class="text">
                            <h1 id="name">Akmal Farhan Raiyan</h1>
                            <h3>Computer Science Student</h3>
                        </div>
                    </div>
                </div>
            </section>

            <section class="about" id="about">
                <div class="row">
                    <div class="col-lg-12">
                        <h2>About</h2>
                    </div>
                </div>
                <div class="details">
                    <div class="row">
                        <div class="col-xs-12 col-md-6 col-lg-6 text-sm-center text-md-right text-lg-right">
                            <h3 id="detail">Details</h3>
                        </div>
                        <div class="col-xs-12 col-md-6 col-lg-6 text-sm-center text-md-left text-lg-left">
                            <p>
                                Name            : Akmal Farhan Raiyan </br>
                                Date of Birth   : 25 August 2000 </br>
                                Adress          : Bogor, Indonesia </br>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="aboutme">
                    <div class="row">
                        <div class="col-xs-12 col-md-6 col-lg-6 text-sm-center text-md-right text-lg-right">
                            <h3 id="aboutme">About me</h3>
                        </div>
                        <div class="col-xs-12 col-md-6 col-lg-6 text-sm-center text-md-left text-lg-left">
                            <p>
                                Born in Niigata on 25th of August 2000 </br>
                                I am currently a Computer Science student </br>
                                in University of Indonesia </br>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <p class="text-center">more</p>
                    </div>
                </div>
            </section>

            <section class="more" id="more">
                <div class="row">
                    <div class="col-lg-3 offset-lg-2">
                        <div class="education">
                            <h3 class="text-center">Education</h3>
                            <p class="text-center">
                                University of Indonesia </br>
                                Bachelor’s degree in computer science </br>
                                2018 - Present </br>
                                </br>
                                SMAN 1 Bogor </br>
                                High school diploma </br>
                                2015 - 2018 </br>
                                </br>
                                SMPN 8 Bogor </br>
                                Middle school diploma </br>
                                2012 - 2015
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="skills">
                            <h3 class="text-center">Skills</h3>
                            <p class="text-center">
                                Python </br>
                                Java </br>
                                HTML </br>
                                CSS
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="interests">
                            <h3 class="text-center">Interests</h3>
                            <p class="text-center">
                                Technology </br>
                                Video Games </br>
                                Fingerstyle Guitar </br>
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            <div class="float">
                <div class="row">
                    <div class="fixed-bottom">
                        <div class="icon">
                            <a href="https://www.instagram.com/akmalfraiyan/" target="_blank">
                                <img src="{% static 'images/instagram.png' %}", alt="Instagram"></a>
                            <a href="mailto:farhanraiyan@gmail.com" target="_blank"></a>
                                <img src="{% static 'images/gmail.png' %}", alt="Gmail"></a>
                            <a href="https://www.linkedin.com/in/akmal-r-a9b5a8134/" target="_blank"></a>
                                <img src="{% static 'images/linkedin.png' %}", alt="Linkedin"></a>
                        </div>
                    </div>
                </div>
            </div>

            <section class="contact" id="contact">
                <div class="row">
                    <div class="col-lg-12">
                        <h2>Contact</h2>
                    </div>
                </div>
                <div class="row icons">
                    <div class="col-xs-12 col-lg-12">
                        <a href="https://www.instagram.com/akmalfraiyan/" target="_blank">
                            <img class="center-block" src="https://img.icons8.com/ios-filled/150/000000/instagram-new.png"></a>
                        <a href="mailto:farhanraiyan@gmail.com" target="_blank"></a>
                            <img src="https://img.icons8.com/ios-filled/150/000000/gmail.png", alt="Gmail"></a>
                        <a href="https://www.linkedin.com/in/akmal-r-a9b5a8134/" target="_blank"></a>
                            <img src="https://img.icons8.com/ios-filled/150/000000/linkedin.png", alt="Linkedin"></a>
                    </div>
                </div>
            </section>
        </div>
    </body>
</html>

homepage/templates/project.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Project</title>
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link href="style.css" rel="stylesheet">
    </head>
    <body>
        <div class="row nav" id="home">
            <div class="fixed-top" class="navbar">
                <div class="float-xs-left float-sm-left float-md-left float-lg-left navbar">
                    <a href="{% url 'homepage:index#home' %}">Home</a>
                    <a href="{% url 'homepage:index#about' %}">About</a>
                    <a href="{% url 'homepage:index#contact' %}">Contact</a>
                    <a href="Project.html">Project</a>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Project</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>.....</h3>    
                </div>
            </div>
        </div>
    </body>
</html>